### ISSUE TITLE
DataSet

### ISSUE THREAD

**Issue by laghbani** [Taeyoung96/FAST_LIO_ROS2#2]
Hello,

Thank you for your efforts. Could you provide us with your dataset, including the ground truth data?

Thank you.

**Comment by Taeyoung96** [comment]
@laghbani  
Hi, I only tested with M2DGR and I converted ROS1 bagfile to ROS2 with [rosbags](https://pypi.org/project/rosbags/)   
There is a detailed description in [their original repository](https://github.com/SJTU-ViSYS/M2DGR), and there are also ground truth files.

**Comment by laghbani** [comment]
> @laghbani Hi, I only tested with M2DGR and I converted ROS1 bagfile to ROS2 with [rosbags](https://pypi.org/project/rosbags/) There is a detailed description in [their original repository](https://github.com/SJTU-ViSYS/M2DGR), and there are also ground truth files.

Thank you for you reply..It would be really nice if we could create a code that compares the fix msg (gps daten) from ROS (as ground truth) with the Odometry msg from Fastlio and evaluates them. do you have some idee about that?

**Comment by Taeyoung96** [comment]
@laghbani 
For comparison with the ground truth of the trajectory, I often use the [evo](https://github.com/MichaelGrupp/evo).  
This repository also supports [ROS2 topics](https://github.com/MichaelGrupp/evo/wiki/Formats#bag--bag2---ros1ros2-bagfile)! :smile:

**Comment by Taeyoung96** [comment]
I've decided that the issue has been answered and close it.
