### ISSUE TITLE
Error of mapping_mid360.launch

### ISSUE THREAD

**Issue by porizou** [Taeyoung96/FAST_LIO_ROS2#3]
Hello,

Thank you for your efforts.

```bash
ros2 launch fast_lio mapping_mid360.launch.py
```

I got the following error when trying to map using LIVOX MID360

```bash
[fastlio_mapping-1] terminate called after throwing an instance of 'rclcpp::exceptions::InvalidParameterTypeException'
[fastlio_mapping-1]   what():  parameter 'mapping.extrinsic_R' has invalid type: Wrong parameter type, parameter {mapping.extrinsic_R} is of type {double_array}, setting it to {integer_array} is not allowed.
[ERROR] [fastlio_mapping-1]: process has died [pid 3637, exit code -6, cmd '/root/ros2_ws/install/fast_lio/lib/fast_lio/fastlio_mapping --ros-args --params-file /root/ros2_ws/install/fast_lio/share/fast_lio/config/mid360.yaml --params-file /tmp/launch_params_1ju2xo2_'].

```

It worked when I modified the mapping : extrinsic_R in mid360.yaml as follows
(Extrinsic_R is int in ouster64.yaml and velodyne.yaml as well)

```yaml
            extrinsic_R: [1., 0., 0.,
                          0., 1., 0.,
                          0., 0., 1.]
```

**Comment by Taeyoung96** [comment]
@porizou 
Thank you for the test with Livox MID 360!  
I have a few questions.

1. Can you show me a visualization of the map when you test with the Livox Mid 360?
2. When you performed your tests, did you utilize real sensors? Or did you use a bag file?

**Comment by porizou** [comment]
@Taeyoung96 

Thank you for your reply
1. here is an image of rviz2 when run in a room

![Screenshot from 2023-10-06 10-54-07](https://github.com/Taeyoung96/FAST_LIO_ROS2/assets/14184141/6bf08a6d-1265-4e7f-a9da-d36b9e82bf8f)

commands executed
```bash
ros2 launch fast_lio mapping_mid360.launch.py
ros2 launch livox_ros_driver2 rviz_MID360_launch.py 
```

2. it is running in real time using actual sensors

**Comment by Taeyoung96** [comment]
@porizou   
Great!! 😄   
Can you give me a pull request based on the mid360 yaml file you successfully mapped?   
Or I could just change the YAML file myself!

**Comment by porizou** [comment]
@Taeyoung96 

Please check the pull request we have made.

Another problem is that I keep getting the following message when running mapping_mid360.launch.py

```bash
[fastlio_mapping-1] Failed to find match for field 'reflectivity'.
[fastlio_mapping-1] Failed to find match for field 'reflectivity'.
[fastlio_mapping-1] Failed to find match for field 'reflectivity'.
[fastlio_mapping-1] Failed to find match for field 'reflectivity'.
[fastlio_mapping-1] Failed to find match for field 'reflectivity'.
[fastlio_mapping-1] Failed to find match for field 'reflectivity'.
[fastlio_mapping-1] Failed to find match for field 'reflectivity'.
[fastlio_mapping-1] Failed to find match for field 'reflectivity'.
[fastlio_mapping-1] Failed to find match for field 'reflectivity'.

```

**Comment by Taeyoung96** [comment]
@porizou 
I merge your PR! Thanks 😄   
I haven't worked with the LIVOX MID 360 so I can't say for sure, but this issue seems to be related to preprocessing.  
I think you need to check that the reflectivity is actually being output from the Livox mid 360 and that the datatype is correct.  
Check out [this line](https://github.com/Taeyoung96/FAST_LIO_ROS2/blob/0a117fb480039ee3a8a106f09175d2c2ad1be222/FAST_LIO/src/preprocess.h#L115) and [preprocessing part](https://github.com/Taeyoung96/FAST_LIO_ROS2/blob/8eae4b28d59fe0348b9d04392fe027c490c45148/FAST_LIO/src/preprocess.cpp#L482).

**Comment by Taeyoung96** [comment]
If this solves the problem, I'll close the issue.  
Please reopen if you have any questions
