### ISSUE TITLE
ROS2 bag for test

### ISSUE THREAD

**Issue by wwtinwhu** [Taeyoung96/FAST_LIO_ROS2#5]
Hello, thanks for your work! Is there any link to download ros2 bag for testing?

**Comment by Taeyoung96** [comment]
@wwtinwhu 
Thanks for your interesting in my work!  
I used [rosbags](https://pypi.org/project/rosbags/) to convert the ros1 bag file to create a ros2 bag file and test it.  
For the ros1 dataset, I used [M2DGR](https://github.com/SJTU-ViSYS/M2DGR).  

However, to my knowledge, there are a few public datasets that have recently been released in ROS2 bag formats.
For example, you could use [GrAco](https://sites.google.com/view/graco-dataset/home?authuser=0)!

**Comment by wwtinwhu** [comment]
@Taeyoung96 Thanks for your suggestion！：）
