### ISSUE TITLE
only run on docker??

### ISSUE THREAD

**Issue by lidarmansiwon** [Taeyoung96/FAST_LIO_ROS2#6]
I need your help. I want to use this package in ubuntu 20.04 foxy with ouster lidar. I have pcd map. 
![image](https://github.com/Taeyoung96/FAST_LIO_ROS2/assets/117976120/656f18f9-8792-46b5-a46d-afbe63e43de7)

![image](https://github.com/Taeyoung96/FAST_LIO_ROS2/assets/117976120/99377882-c7c0-4342-9b00-aff1a91dc2db)

so I edit launch file like picture. but It doesn't work... 
![image](https://github.com/Taeyoung96/FAST_LIO_ROS2/assets/117976120/42f33b07-6df8-4fd5-aa3f-5c7844641369)

Is this package only work on docker? I want to run on native environment! how can i do?

**Comment by lidarmansiwon** [comment]
I think it can be executed even if it's not a docker environment. Because I don't think the code has anything to do with docker. But I can't do anything. it doesn't make map frames. I need your help..

**Comment by Taeyoung96** [comment]
@lidarmansiwon   
I'm not sure I understand exactly what you're experiencing. 
As you say, docker is a tool to make development environments easy, so it should run fine without docker if the environment is set up properly.

What are you facing? 
Are you getting an error in your build? 
Or does it build successfully, but the map doesn't publish?

**Comment by Taeyoung96** [comment]
Also, the picture you sent looks like it corresponds to the [hdl-localization-ROS2](https://github.com/Taeyoung96/hdl-localization-ROS2) repository.

**Comment by lidarmansiwon** [comment]
Thank you for your answer. I had to post a question on the package above, but I think I posted it wrong. I want to use the package above. I tried to modify and localize all the parameters, but it doesn't work.

**Comment by Taeyoung96** [comment]
I'll close the issue for now, but please reopen the issue with more details if you need to resolve the issue.  
Thank you.
